server:
  port: 8007

eureka:
  client:
    service-url:
      defaultZone: http://eureakaservice01.com:8002/eureka,http://eureakaservice02.com:8005/eureka,http://eureakaservice03.com:8006/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

spring:
  application:
    name: spring-cloud-eureka-consumer

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

  compression:
    request:
      enabled: true
      mime-types: ["text/xml", "application/xml", "application/json"]
      min-request-size: 2048
    response:
      enabled: true
