server:
  port: 8015

eureka:
  client:
    service-url:
      defaultZone: http://eureakaservice01.com:8002/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

spring:
  application:
    name: spring-cloud-zuul-consumer

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

  compression:
    request:
      enabled: true
      mime-types: ["text/xml", "application/xml", "application/json"]
      min-request-size: 2048
    response:
      enabled: true

  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000